#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs =  " -r irb/completion"
# Perhaps use a console_lib to store any extra methods I may want available in the cosole
libs << " -r #{File.dirname(__FILE__) + '/../lib/rcsm.rb'}"
libs << " -r #{File.dirname(__FILE__) + '/../lib/console.rb'}"
puts "Loading rcsm gem"
exec "#{irb} #{libs} --simple-prompt"